-- DDL para crear la tabla que almacena imágenes
CREATE TABLE imagenes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(200),
    descripcion VARCHAR2(4000),
    formato VARCHAR2(50),
    imagen BLOB,
    fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMIT;